from openpyxl import Workbook

wb = Workbook()
del wb["Sheet"]

headers = ["question_text","options","correct_answer","difficulty","explanation"]

def add_sheet(name, data):
    ws = wb.create_sheet(title=name)
    ws.append(headers)
    for row in data:
        ws.append(row)

HTML = [
("Difference between <section> and <article>?",
 "Section groups content\tArticle standalone\tSame\tDeprecated",
 "Section groups content","Medium","Section groups related, article is independent."),
("What does srcset do?",
 "SEO\tResponsive images\tLazy load\tCSS",
 "Responsive images","Hard","Serves device-based images."),
("async vs defer?",
 "Same\tAsync runs early defer after parse\tBoth block\tNone",
 "Async runs early defer after parse","Hard","Execution differs."),
("What is Shadow DOM?",
 "CSS\tHidden DOM\tAPI\tAttr",
 "Hidden DOM","Hard","Encapsulation."),
("Hydration?",
 "Attach JS\tCSS\tCache\tRender",
 "Attach JS","Hard","SSR binding."),
("preload?",
 "Early load\tLate\tCache\tAsync",
 "Early load","Medium","Fetch early."),
("contenteditable?",
 "Editable\tStyle\tScript\tNone",
 "Editable","Medium","Allows editing."),
("template?",
 "Store HTML\tRender\tStyle\tScript",
 "Store HTML","Hard","Reusable."),
("rel=noopener?",
 "Security\tSEO\tStyle\tPerf",
 "Security","Hard","Prevents attacks."),
("DOM reflow?",
 "Layout\tPaint\tJS\tAPI",
 "Layout","Hard","Recalc layout."),
("Microdata?",
 "SEO\tCSS\tJS\tAPI",
 "SEO","Hard","Structured data."),
("Block vs inline?",
 "Layout\tColor\tEvent\tNone",
 "Layout","Medium","Display diff."),
("local vs session?",
 "Persist vs session\tSame\tCache\tNone",
 "Persist vs session","Medium","Lifetime."),
("Unknown tags?",
 "Inline\tError\tBreak\tIgnore",
 "Inline","Medium","Handled."),
("Semantic HTML?",
 "Meaning\tStyle\tJS\tNone",
 "Meaning","Medium","Correct tags.")
]

CSS = [
("Specificity?",
 "inline>id>class>element\tclass>id\tid>inline\tNone",
 "inline>id>class>element","Hard","Priority."),
("display vs visibility?",
 "Remove vs hide\tSame\tHide vs remove\tNone",
 "Remove vs hide","Medium","Layout removed."),
("Stacking context?",
 "Layer\tGrid\tFlex\tAnim",
 "Layer","Hard","z-index."),
("will-change?",
 "Hint\tAnim\tLayout\tColor",
 "Hint","Hard","Optimize."),
("Reflow vs repaint?",
 "Layout vs paint\tSame\tPaint vs layout\tNone",
 "Layout vs paint","Hard","Perf."),
("contain?",
 "Isolation\tGrid\tFlex\tAnim",
 "Isolation","Hard","Limit scope."),
("clamp?",
 "Responsive\tAnim\tGrid\tFlex",
 "Responsive","Hard","Sizing."),
("em vs rem?",
 "Parent vs root\tSame\tpx vs %\tNone",
 "Parent vs root","Medium","Units."),
("object-fit?",
 "Image\tLayout\tFlex\tGrid",
 "Image","Medium","Media."),
("CRP?",
 "Render path\tAnim\tJS\tCSS",
 "Render path","Hard","Loading."),
("BEM?",
 "Naming\tLayout\tAnim\tGrid",
 "Naming","Medium","Convention."),
("auto-fit vs fill?",
 "Fit collapse\tSame\tFill collapse\tNone",
 "Fit collapse","Hard","Grid."),
("Compositing?",
 "GPU\tCPU\tLayout\tPaint",
 "GPU","Hard","Rendering."),
("isolation?",
 "Stack context\tLayout\tAnim\tNone",
 "Stack context","Hard","New context."),
("aspect-ratio?",
 "Ratio\tGrid\tFlex\tAnim",
 "Ratio","Medium","Maintain size.")
]

JS = [
("Event loop?",
 "Async system\tThread\tLoop\tTimer",
 "Async system","Hard","Async."),
("Micro vs macro?",
 "Priority\tSame\tExec\tNone",
 "Priority","Hard","Order."),
("Prototype?",
 "Chain\tClass\tCopy\tNone",
 "Chain","Hard","Inheritance."),
("Currying?",
 "Fn returns fn\tLoop\tObj\tEvent",
 "Fn returns fn","Hard","Transform."),
("Debounce vs throttle?",
 "Delay vs limit\tSame\tOpp\tNone",
 "Delay vs limit","Hard","Control."),
("Deep vs shallow?",
 "Ref vs value\tSame\tMem\tNone",
 "Ref vs value","Hard","Copy."),
("IIFE?",
 "Immediate\tLoop\tPromise\tEvent",
 "Immediate","Medium","Exec."),
("Closure leak?",
 "Memory\tSyntax\tLoop\tNone",
 "Memory","Hard","Leak."),
("Call stack?",
 "Exec stack\tHeap\tQueue\tMem",
 "Exec stack","Medium","Calls."),
("Promise.all?",
 "All\tOne\tCancel\tDelay",
 "All","Medium","Parallel."),
("async/await?",
 "Promise\tCallback\tLoop\tEvent",
 "Promise","Hard","Syntax."),
("TDZ?",
 "Before decl\tAfter\tLoop\tScope",
 "Before decl","Hard","Rule."),
("Generator?",
 "Yield\tLoop\tPromise\tObj",
 "Yield","Hard","Iter."),
("Memoization?",
 "Cache\tLoop\tEvent\tPromise",
 "Cache","Hard","Optimize."),
("WeakMap?",
 "GC map\tMap\tArray\tObj",
 "GC map","Hard","Weak ref.")
]

React = [
("Reconciliation?",
 "Diff\tRender\tState\tHook",
 "Diff","Hard","VDOM."),
("Re-render cause?",
 "Both\tState\tProps\tNone",
 "Both","Hard","Triggers."),
("useMemo?",
 "Cache val\tFn\tState\tEffect",
 "Cache val","Medium","Optimize."),
("useMemo vs useCallback?",
 "Val vs fn\tSame\tOpp\tNone",
 "Val vs fn","Hard","Diff."),
("Batching?",
 "Group\tSplit\tDelay\tNone",
 "Group","Hard","Combine."),
("Fiber?",
 "Engine\tHook\tAPI\tLib",
 "Engine","Hard","Core."),
("lazy?",
 "Split\tState\tEffect\tHook",
 "Split","Medium","Dynamic."),
("Suspense?",
 "Fallback\tError\tState\tRoute",
 "Fallback","Hard","Async."),
("Controlled?",
 "State\tDOM\tBoth\tNone",
 "State","Medium","Input."),
("Portal?",
 "Outside DOM\tHook\tAPI\tState",
 "Outside DOM","Hard","Render."),
("Key issue?",
 "Render bug\tStyle\tEvent\tState",
 "Render bug","Hard","List."),
("useReducer?",
 "State\tEffect\tHook\tAPI",
 "State","Medium","Alt state."),
("Hydration error?",
 "SSR mismatch\tCSS\tAPI\tNone",
 "SSR mismatch","Hard","SSR."),
("Concurrent?",
 "Async render\tSync\tBlock\tNone",
 "Async render","Hard","UX."),
("StrictMode?",
 "Debug\tState\tHook\tAPI",
 "Debug","Medium","Dev.")
]

A11y = [
("WCAG?",
 "Guide\tCSS\tJS\tHTML",
 "Guide","Hard","Std."),
("ARIA misuse?",
 "Wrong sem\tStyle\tJS\tNone",
 "Wrong sem","Hard","Bad."),
("Focus trap?",
 "Restrict\tStyle\tEvent\tLayout",
 "Restrict","Hard","Modal."),
("Accessible name?",
 "Label\tCSS\tJS\tLayout",
 "Label","Hard","Compute."),
("Landmark?",
 "Nav region\tStyle\tLayout\tJS",
 "Nav region","Medium","Struct."),
("Skip link?",
 "Avoid repeat\tStyle\tJS\tLayout",
 "Avoid repeat","Medium","UX."),
("Contrast?",
 "4.5:1\t2:1\t1:1\t3:1",
 "4.5:1","Hard","WCAG."),
("aria-hidden?",
 "Hide SR\tVisual\tStyle\tLayout",
 "Hide SR","Medium","SR."),
("Live region?",
 "Dynamic\tStatic\tLayout\tStyle",
 "Dynamic","Hard","Announce."),
("Tab order?",
 "Wrong nav\tStyle\tLayout\tJS",
 "Wrong nav","Medium","UX."),
("Semantic fallback?",
 "Native\tCSS\tJS\tLayout",
 "Native","Hard","Prefer."),
("Accessible modal?",
 "Focus+ARIA\tStyle\tJS\tLayout",
 "Focus+ARIA","Hard","Req."),
("role=presentation?",
 "Remove sem\tAdd\tStyle\tLayout",
 "Remove sem","Hard","Decor."),
("label vs aria?",
 "Visible vs hidden\tSame\tOpp\tNone",
 "Visible vs hidden","Hard","Diff."),
("Keyboard trap?",
 "Focus stuck\tStyle\tLayout\tJS",
 "Focus stuck","Hard","Avoid.")
]

Perf = [
("Main thread?",
 "JS delay\tCSS\tHTML\tNet",
 "JS delay","Hard","Block."),
("Long task?",
 ">50ms\t>1s\t>10ms\tNone",
 ">50ms","Hard","Metric."),
("TTI?",
 "Interactive\tLoad\tRender\tAPI",
 "Interactive","Hard","UX."),
("CLS?",
 "Shift\tSpeed\tAPI\tError",
 "Shift","Hard","Stability."),
("LCP?",
 "Largest\tLoad\tAPI\tCSS",
 "Largest","Hard","Metric."),
("requestIdleCallback?",
 "Idle run\tDelay\tLoop\tAPI",
 "Idle run","Hard","Idle."),
("Code split?",
 "Reduce\tIncrease\tCache\tDelay",
 "Reduce","Medium","Perf."),
("Hydration cost?",
 "JS exec\tCSS\tHTML\tNet",
 "JS exec","Hard","SSR."),
("Service worker?",
 "Cache\tAPI\tCSS\tJS",
 "Cache","Hard","Offline."),
("Prefetch vs preload?",
 "Future vs current\tSame\tOpp\tNone",
 "Future vs current","Hard","Load."),
("Critical chain?",
 "Deps\tCSS\tJS\tHTML",
 "Deps","Hard","Impact."),
("Render blocking?",
 "CSS/JS\tImg\tAPI\tCache",
 "CSS/JS","Hard","Delay."),
("Bundle analyzer?",
 "Analyze\tAPI\tCSS\tJS",
 "Analyze","Medium","Size."),
("Tree shaking?",
 "ESM only\tAll\tCSS\tHTML",
 "ESM only","Hard","Limit."),
("Memory leak?",
 "Unused mem\tAPI\tCSS\tLayout",
 "Unused mem","Hard","Perf.")
]

add_sheet("HTML", HTML)
add_sheet("CSS", CSS)
add_sheet("JavaScript", JS)
add_sheet("React", React)
add_sheet("Accessibility", A11y)
add_sheet("Performance", Perf)

import os

file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "frontend_90_unique_questions.xlsx")
wb.save(file_path)
print(f"Workbook saved successfully to: {file_path}")

file_path